version: 1.0.{build}

os: Visual Studio 2015

platform: x64

#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  matrix:

    - PYTHON: C:\Python36-x64
      PYTHON_VERSION: 3.6

    - PYTHON: C:\Python37-x64
      PYTHON_VERSION: 3.7

install:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version
  - python -m pip install --upgrade pip
  - pip install numpy
  - pip install lazperf


build_script:
 - python setup.py build

test_script:
 - python setup.py test
